# Generated by Django 3.0.6 on 2020-05-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='profile_pic')),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('location', models.CharField(choices=[('AR', 'Arusha'), ('DA', 'Dar es salaam')], max_length=100, null=True)),
                ('religion', models.CharField(choices=[('MU', 'Muslims'), ('CH', 'Christianity')], max_length=100)),
                ('tribe', models.CharField(choices=[('HY', 'Haya'), ('SK', 'Sukluma')], max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'labours',
            },
        ),
    ]
