# Generated by Django 3.0.6 on 2020-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200519_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboursprofile',
            name='work',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
