# Generated by Django 3.0.6 on 2020-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_laboursprofile_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboursprofile',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'default'), ('Da', 'danger')], max_length=20, null=True),
        ),
    ]
