# Generated by Django 3.0.6 on 2020-05-21 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_laboursprofile_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboursprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='laboursprofile',
            name='phone',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('AR', 'Arusha'), ('DA', 'Dar es salaam')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('is_worker', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profile',
            },
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
