# Generated by Django 3.0.6 on 2020-05-21 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200521_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('selected_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LaboursProfile')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='selectedLabour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('selected_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LaboursProfile')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
