# Generated by Django 3.0.6 on 2020-05-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_selectedlabour_selectedlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedlabour',
            options={'verbose_name_plural': 'Selected labour'},
        ),
        migrations.AlterModelOptions(
            name='selectedlist',
            options={'verbose_name_plural': 'Selected list'},
        ),
        migrations.RemoveField(
            model_name='selectedlist',
            name='labour',
        ),
        migrations.AddField(
            model_name='selectedlist',
            name='selected_labours',
            field=models.ManyToManyField(to='core.selectedLabour'),
        ),
    ]
