# Generated by Django 3.0.6 on 2020-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200521_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlabour',
            name='how_many',
            field=models.IntegerField(default=0),
        ),
    ]
