# Generated by Django 3.0.6 on 2020-05-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_selectedlabour_how_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedlabour',
            name='how_many',
        ),
    ]
