# Generated by Django 3.0.6 on 2020-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_selectedlabour_how_many'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedlist',
            old_name='selected_labours',
            new_name='labours',
        ),
    ]
