# Generated by Django 3.0.6 on 2020-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200525_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedlist',
            name='selected_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
