# Generated by Django 3.0.6 on 2020-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200525_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboursprofile',
            name='comments',
        ),
        migrations.AddField(
            model_name='selectedlist',
            name='comments',
            field=models.ManyToManyField(to='core.comments'),
        ),
    ]
