# Generated by Django 3.0.6 on 2020-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200525_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboursprofile',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
