# Generated by Django 3.0.6 on 2020-05-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_address_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlist',
            name='employer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address'),
        ),
    ]
