# Generated by Django 3.0.6 on 2020-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200530_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Employer addresses'},
        ),
        migrations.AddField(
            model_name='laboursprofile',
            name='charges',
            field=models.FloatField(default=100000.0),
        ),
    ]
