# Generated by Django 3.0.7 on 2020-07-21 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20200616_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlist',
            name='charges',
            field=models.FloatField(default=100000.0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
