# Generated by Django 3.0.7 on 2020-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200721_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboursprofile',
            name='charges',
            field=models.FloatField(default=100),
        ),
    ]
