# Generated by Django 3.0.7 on 2020-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200721_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlist',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selectedlist',
            name='charges',
            field=models.FloatField(default=100, null=True),
        ),
    ]
