# Generated by Django 3.0.7 on 2020-07-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200721_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlist',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
