# Generated by Django 3.0.7 on 2020-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200721_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=39, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tribe',
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=39, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tribe',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=39, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tribe',
            },
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='tribe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
