# Generated by Django 3.0.7 on 2020-07-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200721_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Religeon',
            new_name='Religion',
        ),
    ]
