# Generated by Django 3.0.7 on 2020-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200721_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='religion',
            options={'verbose_name_plural': 'Religion'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='tribe',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='work',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
    ]
