# Generated by Django 3.0.7 on 2020-07-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200721_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboursprofile',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Religion'),
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='tribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tribe'),
        ),
        migrations.AlterField(
            model_name='laboursprofile',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Work'),
        ),
    ]
