# Generated by Django 3.0.7 on 2020-07-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200722_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboursprofile',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Work'),
        ),
    ]
