# Generated by Django 3.0.7 on 2020-08-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='labourOfficialDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nida', models.FileField(upload_to='doc')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LaboursProfile')),
            ],
            options={
                'verbose_name_plural': 'Labour doc',
            },
        ),
    ]
