# Generated by Django 3.0.7 on 2020-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200816_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboursprofile',
            name='charges',
            field=models.IntegerField(default=100),
        ),
    ]
