# Generated by Django 3.0.7 on 2020-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200825_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('V', 'Vodacom'), ('A', 'Airtel')], max_length=200, null=True),
        ),
    ]
