# Generated by Django 3.0.7 on 2020-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_selectedlist_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('P', 'Paypal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='selectedlist',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('P', 'Paypal')], max_length=200, null=True),
        ),
    ]
