# Generated by Django 3.0.7 on 2020-09-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200903_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourselectedlist',
            name='ref_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='labourselectedlist',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labourselectedlist',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
