# Generated by Django 3.0.7 on 2020-09-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='order',
            new_name='selected_labour',
        ),
    ]
