# Generated by Django 3.0.7 on 2020-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_contract_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'Contract'},
        ),
        migrations.AddField(
            model_name='laboursprofile',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laboursprofile',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
