# Generated by Django 3.0.7 on 2020-09-14 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200914_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
