# Generated by Django 3.0.7 on 2020-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_contract_signed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=23, null=True)),
                ('contact_email', models.CharField(max_length=30, null=True)),
                ('contact_phone', models.CharField(max_length=30, null=True)),
                ('contact_company', models.CharField(max_length=20, null=True)),
                ('contact_message', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
